projects:
  Flotilla:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-2
        apiId: 4wpcrxdr2bfubbm3si5vtb5lby
        maxDepth: 4
extensions:
  amplify:
    version: 3
